### PR TITLE
Add More Sites and Improve the Consistency

### PR DESCRIPTION
**Pull request by Kazevic**
- Added plenty of sites to the unsafe and safe lists based on CS.RIN.RU;
- Changed "Sega Genesis and Mega Drive" to "Sega Genesis/Mega Drive" and "PS4 to PlayStation 4" because they are the same console and no other abbreviations are being used, respectively;
- Changed one instance of browsers being called "web browser" (it was called "web browser" just once, so I removed the "web" part for it to be consistently called simply "browser");
- Fixed many spaces at the end of the lines.

### CODE REVIEW

**Comment by Kazevic** [comment]
By the way, what do you think of organizing the elements from best to worst? Or at least from most relevant to least relevant? Because, for example, the sites in which you get cracked iOS apps and games are now the first ones under "Direct Download Sites", but they are much less relevant than PC games.

I have a good general idea of each site and I am willing to do it.

**Comment by taskylizard** [comment]
> By the way, what do you think of organizing the elements from best to worst? Or at least from most relevant to least relevant? Because, for example, the sites in which you get cracked iOS apps and games are now the first ones under "Direct Download Sites", but they are much less relevant than PC games.
> 
> I have a good general idea of each site and I am willing to do it.

Feel free to, in a different pull request.

**Comment by Kazevic** [comment]
> > By the way, what do you think of organizing the elements from best to worst? Or at least from most relevant to least relevant? Because, for example, the sites in which you get cracked iOS apps and games are now the first ones under "Direct Download Sites", but they are much less relevant than PC games.
> > I have a good general idea of each site and I am willing to do it.
> 
> Feel free to.

I have decided that I will do it on a separate PR now, because the changes are already big even before actually sorting the sites from best to worst.

**Comment by Kazevic** [comment]
Sorry, I think it is ready now.

**Comment by taskylizard** [comment]
Please resolve the above review.

**Comment by Kazevic** [comment]
Sorry, I swear that I am not seeing anything unusual there.

**Comment by taskylizard** [comment]
It was a pending review, but nevermind that. For rarbg, let's keep the original site instead.

**Comment by Kazevic** [comment]
Oh, ok. The link is "rarbgproxied.org" because it automatically redirects you to that one when you interact with anything, and I have put a link that already sends you to the "games" section. I would value the convenience more, but the project is yours.

**Comment by taskylizard** [comment]
I can definitely feel the convience part, but I also feel like users shouldn't unknowingly log onto proxied sites (which they can handle themselves with a VPN!) without knowing the original.

Also this isn't really my project, it's [r/piratedgames](https://teddit.com/r/piratedgames)' megathread which was mirrored here, except contributors added translations and general qol.

**Comment by Kazevic** [comment]
Oh, I did not think about that... It really is better to leave it as it was before then.

Yes, I know about that, but I would consider it as a fork of the original r/PiratedGames megathread now, not only just a backup version. Also, done.

**Comment by Kazevic** [comment]
You are welcome!

**Comment by taskylizard** [comment]
Everything looks good, but where does magipack source their uploads from? I can't seem to find anything about it.

**Comment by Kazevic** [comment]
Well, that is... a good question...

**Comment by taskylizard** [comment]
Sources for the downloads are kinda important, so it's best not to list them for now.

**Comment by Kazevic** [comment]
Ok, done now. Please, ignore the "Gamesdue" lol

**Comment by taskylizard** [comment]
LGTM, thank you for your contribution!

**Pull request merged**
